server:
  port : 8010
spring:
  application:
    name: api-gateway
  servlet:
    multipart.max-file-size: 1024MB
    multipart.max-request-size: 1024MB

zuul:
  routes:
    api-ucenter:
      path: /ucenter/**
      url: http://localhost:9002/ucenter
    api-user:
      path: /user/**
      url: http://localhost:8182/user
  sensitive-headers:


